name: release elastic ansj plugin
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "git tag to release"
      es-version:
        required: true
        description: 'es version'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      - run: mkdir staging && cp target/releases/* staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{github.event.inputs.tag}}"
          title: "支持es${{github.event.inputs.es-version}}版本的分词插件"
          prerelease: false
          files: |
            staging/*.zip